# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default:
            url: '%env(ELASTICSEARCH_URL)%'
            username: 'elastic'
            password: 'secretP4ssw0rd'
            #headers:
                #Authorization: "Basic ZWxhc3RpYzpzZWNyZXRQNHNzdzByZA=="
    indexes:
        post: null

    serializer: ~